### ISSUE TITLE
Feature Request - Config option to open at last place of closing

### ISSUE THREAD

**Issue by b0bst3r** [gigaherz/Guidebook#1]
Don't know if you're taking requests but my pet peeve with books is when you close them you have to page through to the last point where you was reading.  Some books don't do this and it makes such a big difference.

Can I request please for them to do this so they reopen at the place you was last reading?

If not can you make a possible config option to do it?

**Comment by gigaherz** [comment]
Ah, yes, it is something that had slipped my mind. I wasn't quite sure how to approach this, so I kept delaying it.

I see two options:
1. "Remember" the last position on the internal book data, which would be local to the client, would NOT persist across restarts, and it would be shared by all copies of the same book.
2. Add a "bookmark" system that gets stored in the book item itself. This would persist across restarts, be specific to each copy of the book, and it would transfer over to other players. The issue is, this would require sending the bookmark info to the server, and having the server modify the ItemStack, which doesn't seem quite right.

I'll give it some more thought after I leave work.

**Comment by gigaherz** [comment]
I decided to to both, sortof. I'll make the "browsing state" persistent, so that you can close a book, and reopen it, and it remembers the last state, including browsing history (so you can navigate back).

On top of that, I'm adding to my TODO list, to create a bookmarks system that would let you navigate to certain points of a book.

**Comment by gigaherz** [comment]
v1.3.1 is out, and it includes the fix. Have fun.
