### ISSUE TITLE
Suggestion: add the align attibute to images.

### ISSUE THREAD

**Issue by Wissi** [gigaherz/Guidebook#14]
Images can't be "centered" or aligned to the right on the page. 

The 'tx' and 'ty' are only for drawing the image but image will always be on the left of the page.

The Image can't be nested in &lt;p&gt; tag either.

Can the attribute: &nbsp;&nbsp;&nbsp;&nbsp;  align=""   &nbsp;&nbsp;&nbsp;&nbsp;  with center and right be added to the &lt;image&gt; tag ?
perhaps I'm misunderstanding the proper use of the 'tx' and 'ty' ?

Any way to know if your awesome work will include the &lt;span&gt;  tag soon?

Thanks. LOVE your mod it's extremely useful we love it.

**Comment by Necr0** [comment]
"tx" and "ty" are used to set origin of the image on the given texture. So "tx", "ty", "tw" and "th" are used to form a rectangle on the texture to tell it where to read the image from. What you want are the "x" and "y"(without the "t") attributes. "x" and "y"are used for positioning the image on the page relative to the current context. "h" and "w" are used to define the dimensions of the image on the page and I think it clamps the image meaning it will always be rescaled to fit the height and width given.

**Comment by Wissi** [comment]
Perfectly clear. Working flawlessly.

Quick question, could the page "margins" be configured for more or less space?

Thank you.

**Comment by gigaherz** [comment]
There's a lot of things I want to add in the future. One of my top priorities is to get a release out with the recent pull requests, and then my plan is to implement "span elements", that is, elements that are nested inside &lt;p&gt;, and can have images and their own custom formatting. 
However, implementing span elements will mean I have to write my own text splitting system, because micecraft's own doesn't do things THAT advanced.

**Comment by Wissi** [comment]
Well, looking forward to the &lt;span&gt; tags. 
Hope U can get your pull requests out smoothly and soon too.

Thanks.
