### ISSUE TITLE
Bug - font size resize the whole book

### ISSUE THREAD

**Issue by gdarai** [gigaherz/Guidebook#43]
Hi.. I need hint or I am just reporting bug: Adding fontSize="0.6" to the book tag changes the size of the whole book.
I have 2 books added, one without fontSize and second with it.
![2018-05-07_22 49 46](https://user-images.githubusercontent.com/26735549/39724836-26d9ee44-524a-11e8-880c-74cff6234179.png)
![2018-05-07_22 49 53](https://user-images.githubusercontent.com/26735549/39724837-2841b01e-524a-11e8-9129-0d6f340738a8.png)
Do you know how to get corret fontSize withour resizing the book?
It is possible that it is a mod interaction conflict, since on smaller modpack it behaves differently/correctly.

**Comment by gigaherz** [comment]
I have a certain algorithm to decide the actual size of the book. I tried to keep the font scale in fixed numbers, so like 1x, 2x, 3x... so it can happen that when calculating the new book scale, it will choose a smaller size.

Let me give an example: suppose your normal gui scale is 7x, and you choose 0.6, that results in a font size of 4.2, which would look uneven. So instead of keeping the book in the original size and scaling the text as 4.2x, I round the font scale down to 4x, and then scale the book model to 95% of the original size, to compensate. 

But in your case, something else seems to be going on, since the final size should not be THAT small... what book size did you configure in the mod settings?

**Comment by gdarai** [comment]
I did not... what setting and where it should be?

**Comment by gdarai** [comment]
Hi hi... setting the size to 3 = large broke even the good book:
![2018-05-07_23 47 11](https://user-images.githubusercontent.com/26735549/39726939-08d559e0-5251-11e8-9574-8c2b9472d951.png)

**Comment by gdarai** [comment]
So what do you recommend? The font size 1 is too large... I need to shrink down the text, not make it larger. What should I put there in?

**Comment by gigaherz** [comment]
Yes sorry, changing the size is bugged currently, you have to reload resources (F3+T) or restart the game...

**Comment by gdarai** [comment]
Oh, I tried, the screenshots are after the whole game restarted. So, unfortunately no, it is not just a question of restarting the game. size = -1 and fontSize = 0.5 does the same as the original size = -1 and fontSize = 0.6... I will try size = 3 if it will be different after restart to have the full image.

**Comment by gigaherz** [comment]
The default gui scale works well with my screen, but I have 2560x1440, so that may not be true for you. The issue with books being too small or too big, I have to fix. I wrote it on this screen so I didn't fully test enough sizes to know that it worked well for everyone. Keep this issue open so I remember :)

**Comment by gdarai** [comment]
Ok, thank you. I will for now let my players suffer (come on, I put a lot effort in it and it is sort of readable.) and if I will go out from beta and still have this issue, I will rewrite the book in the standard scale, which somewhat works. For the full information, my monitor is 1920*1080 minecraft setting 1024*768, gui size Large and the issue was for gbook size -1 and fontSize = 0.6.

**Comment by gigaherz** [comment]
I have just uploaded version 2.5, which contains many experimental features, including improvements to the logic for calculating the book size, and should behave better overall. However due to the experimental nature of the HUGE changes to the mod's internals, I have marked it as alpha. Feel free to test (it's under review and should be available soon), and tell me if you can find any issue in it!
