### ISSUE TITLE
Crash while loading

### ISSUE THREAD

**Issue by kave777** [gigaherz/Guidebook#47]
there is a crash while loading minecraft .
here is the crash - https://paste.ee/p/vcnR4
minecraft version - 1.12.2
forge - 14.23.4.2707   
guide book version - 2.0.1

**Comment by kave777** [comment]
I have updated gbook to 2.5.0 , still the same problem

**Comment by gigaherz** [comment]
I have no idea what could possible cause that crash.

![image](https://user-images.githubusercontent.com/685851/41200532-87763f7a-6ca6-11e8-9729-a4fd87d7e226.png)

The files certainly exist in the mod.

Is this a modpack I could get from curse or something?

**Comment by gigaherz** [comment]
Also, is there any chance you can get the entire log and not just the crash report? Thre's a chance the real issue appeared earlier, and is not included in the crash report data.

**Comment by Gabrielcmf** [comment]
The issue isn't on Guidebook's part, it seems to be caused by the newest version of 
Shadowfact's Forgelin, try using a previous version of it and it should work.

**Comment by aking4125** [comment]
I don't even have that mod and I got a crash with 2.5.2 of Guidebook. I used 2.5.1 before and downgraded and I'm getting the same crash over and over.

**Comment by gigaherz** [comment]
What version of Forge are you using?

**Comment by gigaherz** [comment]
As mentioned in issue #48 -- there's a chance those crashes are caused by naughty mods registering handlers for BookRegistryEvent in a dedicated server (the regsitry is client-only).

To work around those misbahaving mods and provide a better experience for the user, v2.5.3 should prevent that (technically invalid) behaviour from causing a crash.

If you want to test this new build, it's out on curseforge: https://minecraft.curseforge.com/projects/guidebook/files/2573054

I'm assuming the crash is fixed, but feel free to comment if that's not the case.
