### ISSUE TITLE
Crash at client start since v2.5.1

### ISSUE THREAD

**Issue by lebanni** [gigaherz/Guidebook#51]
MC 1.12.2
Forge 14.23.4.27.08
Guidebook 2.5.3

[crash-2018-06-16_15.35.17-client.txt](https://github.com/gigaherz/Guidebook/files/2108174/crash-2018-06-16_15.35.17-client.txt)

**Comment by TheFloydman** [comment]
The error (java.lang.NoClassDefFoundError: gigaherz/guidebook/client/BookRegistryEvent) is caused because the mod that adds the guidebook (MineColonies in this case) has not directed Forge to load the mod AFTER guidebook. Contact the author of MineColonies and ask them to add "after:gbook" as a dependency in their main class.
