### ISSUE TITLE
Guidebook 1.12.2 Version: 2.9.0 Crash by start

### ISSUE THREAD

**Issue by Titoo8899** [gigaherz/Guidebook#83]
hi,
the game crash when we have the newest Version of the Guidebook in the mod folder. Please fix this in the next update.

**Comment by gigaherz** [comment]
Please provide a crash log. I can't fix it if you don't show me a crash log.

**Comment by gigaherz** [comment]
Oh one thing: if you use the recommended build of forge, it will not work. it has to be forge 2779 or newer, latest would be ideal since it has the most fixes.

**Comment by SoupOfDepression** [comment]
Got same bug after updating my 84 mods. I have the log.
[crash-2019-05-08_18.40.59-client.txt](https://github.com/gigaherz/Guidebook/files/3159557/crash-2019-05-08_18.40.59-client.txt)

**Comment by gigaherz** [comment]
Huh... what the heck happened. Seems the jar I uploaded was a development build rather than a proper build. I wonder how I managed that mixup... Welp 2.9.1 incoming!

**Comment by gigaherz** [comment]
v2.9.1 is approved on CurseForge. This release should fix that crash. @SoupOfDepression 

https://minecraft.curseforge.com/projects/guidebook/files/2708746

I don't know if it will fix the original issue since I never saw a crash log for it, but I will assume so. If I'm wrong, let me know and i'll reopen.
